### ISSUE TITLE
向大佬请教

### ISSUE THREAD

**Issue by 1785661184** [xlorne/le-examples#1]
大佬你好，请问通过类似策略模式这样处理service，是否也有利于复杂业务的拆解，或者一定程度上提高业务代码的可读性，易分析性，还是说其实是把会把业务的一部分逻辑转移到了代码结构设计上

**Comment by xlorne** [comment]
复杂业务的拆解，需要通过业务聚合与抽象来实现，这种方式主要实现业务的拓展性增加业务的适配能力。
